### ISSUE TITLE
4.6.0?

### ISSUE THREAD

**Issue by imrman** [droboports/crashplan#21]
any chance for 4.6.0 update for Drobo5N?

**Comment by ricardopadilha** [comment]
Version 4.5.2 did a self-upgrade to 4.6.0 successfully. I just had to restart it at the end. Did the self upgrade fail for you?

**Comment by jcollao** [comment]
Hi Ricardo!

Mine did not self  upgrade. Any ideas?

thanks!

**Comment by ricardopadilha** [comment]
Crashplan has, as usual, altered the terms of our deal. According to this post from the [Drobospace forums](http://www.drobospace.com/forums/showthread.php?tid=141634&pid=197869#pid197869) 4.6.0 now requires bash to be installed on the system.

I'm working on getting that fixed, but for now you can install the [bash DroboApp](https://github.com/droboports/bash) so that Crashplan can update itself. Keep an eye on the logs (under /tmp/DroboApps/crashplan, or through the configuration webui) to make sure that the updates took place.

**Comment by ricardopadilha** [comment]
Version 4.6.0.5 is now available from Drobo Dashboard. I recommend installing/upgrading from there.
