### ISSUE TITLE
4.2.0 Java requirement clarification

### ISSUE THREAD

**Issue by deekayen** [droboports/crashplan#6]
I've completely uninstalled Crashplan 3.7.0 (saving my backupArchives) to get my 4.2.0 install going on my 5N, but the Crashplan service isn't starting. Would you clarify whether 4.2.0 expects Java 7 or 8? I had 3.7.0 running with Java 7.

**Comment by deekayen** [comment]
After installing the Java 8 tarball from http://www.droboports.com/app-repository/java8/, Crashplan 4.2.0 started on my 5N.

**Comment by ricardopadilha** [comment]
I'm sorry, I forgot to mention that 4.2.0 now uses java8. This is not a requirement from CrashPlan, I decided to bump the requirement due to the fact that Java 7 is officially deprecated<sup>[1]</sup>, and will be no longer supported. I have updated the crashplan releases page accordingly.

[1]: https://www.java.com/en/download/faq/java_7.xml
